### ISSUE TITLE
Convexity is not an available parameter for import_()

### ISSUE THREAD

**Issue by 3marcusw** [SolidCode/SolidPython#106]
When using import_() the convexity parameter is not available, which can be an essential parameter for some files to be workable.

**Comment by etjones** [comment]
Added. This was overlooked a long time ago. I've never used any files that needed convexity at all, so I've never really been sure what it was for. Out of curiosity, can you point me to a file that needs a convexity argument? I'd like to understand what OpenSCAD is doing with it.
