### ISSUE TITLE
linear_extrude does not accept segments argument

### ISSUE THREAD

**Issue by ali1234** [SolidCode/SolidPython#107]
The OpenScad `linear_extrude` accepts `$fn` but the SolidPython version does not accept `segments`.

Example:

```
linear_extrude(h=10, twist=30, segments=10)(
    square([3, 3, 3], center=True)
)
```

**Comment by nickc92** [comment]
Yes, that fails for me too.  I'll look into it!

**Comment by nickc92** [comment]
Ok, try:
```
linear_extrude(h=10, twist=30, slices=10)(
    square([3, 3, 3], center=True)
)
```
I think in OpenSCAD you can use either `$fn` or `slices`, but here you must use `slices`.
