### ISSUE TITLE
Offset should accept zero as arguments

### ISSUE THREAD

**Issue by yaqwsx** [SolidCode/SolidPython#147]
In OpenSCAD, offset can accept zero for `r` or `delta`. Unfortunately, SolidPython does not. The problem is in: https://github.com/SolidCode/SolidPython/blob/f79d68c7fbb82f1763ca7de1ec24576fbfc02585/solid/objects.py#L418-L426

Instead of `if variable:` should be `if variable is not None`.

Use case: When `r` is a user-supplied argument.

**Comment by etjones** [comment]
Thanks, that’s a good catch. I’ll push a change later today
