### ISSUE TITLE
error while making a pipe with extrude along path

### ISSUE THREAD

**Issue by vert-rouge** [SolidCode/SolidPython#204]
Hi,

I’m trying to make a pipe. My code is heavily inspired by the examples.

Here is the code.
[pipe_problem.py.txt](https://github.com/SolidCode/SolidPython/files/11129274/pipe_problem.py.txt)

In OpenScad, I get the preview but an error pop when I render:
```
Rendering Polygon Mesh using CGAL...
ERROR: CGAL error in CGALUtils::applyBinaryOperator difference: CGAL ERROR: assertion violation! Expr: itl != it->second.end() File: /usr/include/CGAL/Nef_3/SNC_external_structure.h Line: 1150 
CGAL Cache insert: difference(){polyhedron(points=[[4.24264 (4505224 bytes)
```

I may have done something wrong, but I can’t figure what.

**Comment by jeff-dh** [comment]
Don't have the time to get into detials, but if I understand correctly
what you're trying to do, I would do it -- with solid2 -- like this:

```
from solid2.extensions.bosl2 import *

path = [ [0, 0, 0], [33, 33, 33], [66, 33, 40], [100, 0, 0], [150,0,0] ]
path_extrude(path)(circle(5)-circle(2)).save_as_scad("pipe.scad")
```

Note: this is SolidPython2 (https://github.com/jeff-dh/SolidPython)!
