### ISSUE TITLE
Can we unpin prettytable?

### ISSUE THREAD

**Issue by jfly** [SolidCode/SolidPython#207]
prettytable is currently pinned at 0.7.2 (due to some weird bug with poetry? see [this commit](https://github.com/SolidCode/SolidPython/commit/f71ccd9adfc2389c82eba7c7022a8f16c018119a)). It has been a while since 2019, maybe whatever bug there was in poetry doesn't exist anymore.

**Comment by jeff-dh** [comment]
Checkout SolidPython v2. It does not depend / use prettytable anymore.

https://github.com/jeff-dh/SolidPython/tree/master-2.0.0-beta-dev

**Comment by jfly** [comment]
Sounds good. We'll focus our efforts on moving from solidpython to solidpython v2.
