### ISSUE TITLE
combine translate and rotate

### ISSUE THREAD

**Issue by MaierJuerg** [SolidCode/SolidPython#211]
in openscad I use:
```
translate([10,0,5])
rotate([0,90,0])
cylinder(d=50, h=200);

```
can't figure out how to write that with solid as it is not accepting this statement:
`translate((10,0,5))rotate((0,90,0))(cylinder(d=50, h=200))`

**Comment by jeff-dh** [comment]
cylinder(...).translate(...).rotate(...)

or:

rotate(...)(translate(...)(cylinder(...)))

and / or take a look at the examples....

05.09.2024 10:33:42 MaierJuerg ***@***.***>:

**Comment by MaierJuerg** [comment]
I have installed solid as pip install solidpython
it is version 1.1.3 and I run it with python 3.12 on ubuntu
rotate(...) will add a colon ; after the command making it useless!
runtime error for .rotate
'cylinder' object has no attribute 'rotate'

**Comment by jeff-dh** [comment]
https://github.com/jeff-dh/SolidPython/blob/master-2.0.0-beta-dev/solid2/examples/05-access-style-syntax.py

https://github.com/jeff-dh/SolidPython/blob/master-2.0.0-beta-dev/solid2/examples/04-convenience.py

05.09.2024 11:46:27 MaierJuerg ***@***.***>:

**Comment by MaierJuerg** [comment]
thanks but these examples use solid2. how to install that?

**Comment by jeff-dh** [comment]
https://github.com/jeff-dh/SolidPython/wiki

05.09.2024 13:06:00 MaierJuerg ***@***.***>:

**Comment by MaierJuerg** [comment]
Great, thanks, looks much better now!
