### ISSUE TITLE
Feature request: Python 3 support?

### ISSUE THREAD

**Issue by dmopalmer** [SolidCode/SolidPython#23]
Is there a roadmap to support Python3?

The stock pyeuclid doesn't support python3, but the https://github.com/ezag/pyeuclid fork seems to install without complaint.

**Comment by etjones** [comment]
Since PyEuclid is stuck in maintainer-change hell, I've changed the internal dependency to the Py3-safe `euclid3` package.  Haven't yet updated the PyPI package, but hope to do so today.  Cloning master works on Py2 or Py3, `pip install solidpython` should work shortly as well.
