### ISSUE TITLE
Be less agressive with import *

### ISSUE THREAD

**Issue by eric-wieser** [SolidCode/SolidPython#60]
Right now, `from solid import *` adds to globals:

1. these clearly unwanted names
    * `os`
    * `sys`
    * `re`
    * `inspect`
    * `subprocess`
    * `tempfile`
    * `solidpython`

2. these possibly internal names (tick the ones we should remove?)

    * [ ] `parse_scad_callables`
    * [ ] `extract_callable_signatures`
    * [ ] `sp_code_in_scad_comment`
    * [ ] `new_openscad_class_str`
    * [ ] `scad_render_to_file`
    * [ ] `py2openscad`
    * [ ] `IncludedOpenSCADObject`
    * [ ] `OpenSCADObject`
    * [ ] `calling_module`
    * [ ] `OpenSCADObject`
    * [ ] `scad_render_animated`
    * [ ] `objects` (if the user wanted this, they should probably have just done `from solid import objects`)
    * [ ] `scad_render_animated_file`
    * [ ] `non_rendered_classes`
    * [ ] scad_render

For the ones in the second list, simply prefixing internal names with an underscore is sufficient. To remove the top names, the best solution is to use `__all__`

**Comment by etjones** [comment]
What GH-Markdown trickery is this?  Nice list.  The only names in either category that really ought to remain in the global namespace are `scad_render<*>`.  While the other functions get called internally, there's no reason a developer would use them while actually making geometry.
