### ISSUE TITLE
Fork the dependency

### ISSUE THREAD

**Issue by KOLANICH** [SolidCode/SolidPython#90]
The dependency of SolidPython (euclid) is unmaintained. There is a more recent fork https://github.com/ezag/pyeuclid , but it is unmaintained too.

I suggest to
1 fork https://github.com/ezag/pyeuclid into the org.
2 review pull requests : https://github.com/ezag/pyeuclid/pulls and merge the ones considered needed

**Comment by etjones** [comment]
This was a hassle for a long time.  Instead, I switched things to Euclid3, (https://github.com/euclid3/euclid3)  which resolved the version issues we had.  It's not under active development, but neither is SolidPython
