### ISSUE TITLE
Thread bug re neck_in_degrees and neck_out_degrees?

### ISSUE THREAD

**Issue by nerdfever** [SolidCode/SolidPython#92]
When I use screw_thread.thread() with the neck parameters I get:

* if neck_in_degrees == neck_out_degrees:  things work as expected

but

* if neck_in_degrees != neck_out_degrees: odd shapes, not as expected
* if neck_in_degrees > 0 and neck_out_degrees == 0:  float division by zero

(Divide-by-zero error is in screw_thread.py, line 113)

**Comment by etjones** [comment]
Nice catch.  Two bugs here. Fixed
